services:
  app-mongo:
    container_name: stac-fastapi-mongo
    image: stac-utils/stac-fastapi-mongo
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev.mongo
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8084
      - RELOAD=true
      - ENVIRONMENT=local
      - BACKEND=mongo
      - MONGO_DB=stac
      - MONGO_HOST=mongo
      - MONGO_USER=root
      - MONGO_PASS=example
      - MONGO_PORT=27017
    ports:
      - "8084:8084"
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    depends_on:
      - mongo
    command:
      bash -c "./scripts/wait-for-it-es.sh mongo-container:27017 && python -m stac_fastapi.mongo.app"

  mongo:
    container_name: mongo-container
    image: mongo:7.0.5
    hostname: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
